labels: []
# title: ''
body:
  - type: textarea
    id: body
    attributes:
      label: Add a body
      description: Add the question body
      placeholder: Ask a question, start a conversation, or make an announcement
      # value: ''
      # render: bash
    validations:
      required: true
