name: Default
description: Default issue template
assignees: []
labels: []
# title: ''
# type: ''
projects: []
body:
  - type: textarea
    attributes:
      label: Key tasks
      description: List of tasks to be completed
      placeholder: |
        - Task 1
        - Task 2
        - Task 3
      # value: ''
      # render: bash
    validations:
      required: true
